# Generated by Django 3.2.8 on 2021-10-29 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_remove_post_image'),
        ('fundtrans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hh.post'),
        ),
    ]
