# Generated by Django 3.2.8 on 2021-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundtrans', '0003_auto_20211029_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=50),
        ),
    ]
