# Generated by Django 3.2.8 on 2021-10-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funds',
            field=models.IntegerField(default=3000),
        ),
    ]
