# Generated by Django 3.2.8 on 2021-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_post_donation_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='donation_amt',
            new_name='curr_amt',
        ),
        migrations.AddField(
            model_name='post',
            name='target_amt',
            field=models.IntegerField(default=0),
        ),
    ]
