# Generated by Django 3.2.8 on 2021-10-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_auto_20211027_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='none', upload_to='post_pics'),
        ),
    ]
