# Generated by Django 3.2.8 on 2021-10-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
